# Twitch configuration
twitch:

  # if this is enabled put the Oauth token into a text file called: 'password.txt'
  externalOAuth: true

  # If external oAuth is enables this can be left as it is.
  oAuth: 'oAuth:abdefghijklmnopqrstuvwxyz1234567890'

  # The bots nickname ~ useless cause this name is not shown
  nickname: 'B1naryB0t'

  # The bots channel ~ the bot is joining this channel and listen to the messages written on this ch for commands, games, etc.
  channel: 'binarybave'

  # The bots channel ~ the bot is joining this channel and listen to the messages written on this ch for commands, games, etc.
  prefix: '!'

# MySQL configuration
mysql:
  username: root
  password: 123456789
  database: TwitchBot-Dave
  hostname: localhost
  port: 3306
  externalPassword: true

# Web configuration
web:
  # The web listening port (Default: 8087)
  port: 8087

  # The server address where the files are located (Default: localhost)
  server: localhost

# Game configurations
game:
  # Catch Game
  catch:

    # enables the use of the game
    enable: true

    # no: the Message given if there is currently no catch game on going.
    no: '%name%, There is currently no catch on going!'

    # Pool settings: lets the twitch users enter a pool and win individually and not the fastest one wins.
    pool:
      # Enables the pool phase
      enable: true

      # Time how long the pool phase is going
      # NOTE: put nothing in that is greater than (2^31)-1.
      time: 10000

      # OBS delay in milliseconds
      # NOTE: put nothing in that is greater than (2^31)-1.
      delay: 2000

      # This are the messages which are give out the catch users
      messages:

        # If the pool is enabled and there is no catch going the user will be notified by this message.
        # Use '%name%' to display the users name.
        closed: '%name% The Pool is currently closed, we do not accept more!'

        # If a catch is currently on going and the pool is enabled this message is send to the user.
        # Use '%name%' to display the users name.
        ongoing: '%name%, you have been added to the Pool!'

        # The Message above is only shown if this boolean is set to true!
        ongoingenable: true

    # When the timer cooldown expires a new catch game is started.
    # Between the min and max value will the cooldown be set.
    timer:

      #5min
      # NOTE: put nothing in that is greater than (2^31)-1.
      min: 300000

      #10min
      # NOTE: put nothing in that is greater than (2^31)-1.
      max: 600000

    # When a catch is going on the first User typing !catch will be rewarded.
    winner:
      # The massage the user(winner) will get.
      message: '%name% won the catch!'

      # The rewards the user(winner) will get.
      reward:

        # Use '%name%' to display the name and %min_max% to generate a random number between the min value and the max value.
        # NOTE: the message is shown to the chat for 3rd-party bot use!
        # NOTE: the value (itc. 20187) is a 'String' it can be as big as the bot can ACCEPT it. Otherwise your 3-rd Party bot will throw exceptions!
        command: '!addpoints %name% %min_max%'
        # command: '!addpoints %name% 20187'

        # Enables the reward mechanism and sends the message above with the name of the user(winner).
        enable: true

        # This is the min value for the function '%min_max%' in the command entry of this tree.
        # # NOTE: put nothing in that is greater than (2^31)-1.
        min: 60

        # This is the max value for the function '%min_max%' in the command entry of this tree.
        # NOTE: put nothing in that is greater than (2^31)-1.
        max: 1337

      # If the this is enabled the first user typing !catch will be ignored and responded with the message below.
      repeat:

        # If this mechanism is not enabled (eg. enable: false) this message is displayed to the user entered the command first.
        # Use '%name%' to display the name of the user.
        message: '%name% you already won last time. I will let someone else win for fairness!'

        # Enables the mechanism who lets the last user(winner) win again.
        enable: true

    # The image shown on the web plane for the users.
    # This image is only shown during an on going catch game.
    image:
      location: 'html/catch-game.png'

    # When another user typed !catch right after the first one(winner) this message is being shown to the user/chat.
    missed:
      #10sec
      # This is just the time users have to type catch after the first one(winner).
      # If the catch is over about 10 Seconds(the time below) ago !catch will show the 'no' again.
      time: 10000

      # The message shown to the users who just passed the catch.
      message: 'Sorry %name%, you just missed it. %winner% were faster then you!'

      # Enables the missed message.
      enable: true

  # Dice Game
  dice:
    # Enables the Dice game.
    enable: true

    # Sets the max bound rate of the dice (eg. 6 means the max number which can be rolled is a 6).
    # NOTE: put nothing in that is greater than (2^31)-1.
    max: 6

