# Twitch configuration
twitch:

  # if this is enabled put the Oauth token into a text file called: 'password.txt'
  externalOAuth: true
  # If external oAuth is enables this can be left as it is.
  oAuth: oAuth:abdefghijklmnopqrstuvwxyz1234567890

  # The bots nickname ~ useless cause this name is not shown
  nickname: B1naryB0t

  # The bots channel ~ the bot is joining this channel and listen to the messages written on this ch for commands, games, etc.
  channel: binarydave
  prefix: '!'
 

# Web configuration
web:
  # the web listening port
  port: 8087
  
  server: localhost

# Games
game:
  # Catch Game
  catch:

    # enables the use of the game
    enable: true

    # no: the Message given if there is currently no catch game on going.
    no: There is currently no catch on going!

    # When the timer cooldown expires a new catch game is started.
    # Between the min and max value will the cooldown be set.
    timer:
      #5min
      min: 300000
      #10min
      max: 600000

    # When a catch is going on the first User typing !catch will be rewarded.
    winner:
      # The massage the user(winner) will get.
      message: '%name% won the catch!'
      # The rewards the user(winner) will get.
      reward:
        # NOTE: the message is shown to the chat for 3rd-party bot use!
        message: '!addpoints %name% 1337'
        enable: true
      # If the this is enabled the first user typing !catch will be ignored and responded with the message below
      repeat:
        message: 'You already won last time. I will let someone else win this time!'
        enable: true

    # The image shown on the web plane for the users.
    # This image is only shown during an on going catch game.
    image:
        location: html/catch-game.png

    # When another user typed !catch right after the first one(winner) this message is being shown to the user/chat;
    missed:
      #10sec
      # This is just the time users have to type catch after the first one(winner).
      # If the catch is over about 10 Seconds(the time below) ago !catch will show the 'no' again
      time: 10000
      # The message shown to the users who just passed the catch
      message: 'Sorry you just missed it. %name% were faster then you!'
      # Enables the missed message
      enable: true

  # Dice Game
  dice:
    # Enables the Dice game
    enable: true
    
    max: 6

